name: Test all

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10.0'
          architecture: 'x64'
      - name: install
        run: make install
      - name: pylint
        run: make pylint
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10.0'
          architecture: 'x64'
      - name: install
        run: make install
      - name: doctests
        run: make doctests
